[package]
name = "smart_house_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "*"
chrono = "0.4.31"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eframe = "0.19.0"

[dev-dependencies]
# test only deps
float-cmp = "*"